# Generated by Django 2.0.4 on 2018-05-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0004_auto_20180507_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter_id',
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ojss_app.RecruiterProfile'),
            preserve_default=False,
        ),
    ]
