# Generated by Django 2.0.4 on 2018-05-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0005_auto_20180507_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_description',
        ),
    ]
