# Generated by Django 2.0.4 on 2018-05-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0007_recruiterprofile_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerSkillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(max_length=255)),
                ('skill2', models.CharField(blank=True, max_length=255, null=True)),
                ('skill3', models.CharField(blank=True, max_length=255, null=True)),
                ('skill4', models.CharField(blank=True, max_length=255, null=True)),
                ('skill5', models.CharField(blank=True, max_length=255, null=True)),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ojss_app.SeekerProfile')),
            ],
        ),
    ]
