# Generated by Django 2.0.4 on 2018-05-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0008_seekerskillset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seekerskillset',
            old_name='skill1',
            new_name='skill_1',
        ),
        migrations.RenameField(
            model_name='seekerskillset',
            old_name='skill2',
            new_name='skill_2',
        ),
        migrations.RenameField(
            model_name='seekerskillset',
            old_name='skill3',
            new_name='skill_3',
        ),
        migrations.RenameField(
            model_name='seekerskillset',
            old_name='skill4',
            new_name='skill_4',
        ),
        migrations.RenameField(
            model_name='seekerskillset',
            old_name='skill5',
            new_name='skill_5',
        ),
    ]
