# Generated by Django 2.0.4 on 2018-05-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0010_auto_20180508_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='seeker_id',
            new_name='seeker',
        ),
    ]
