# Generated by Django 2.0.4 on 2018-05-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0011_auto_20180508_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
