# Generated by Django 2.0.4 on 2018-05-09 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0014_application_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('A', 'APPLCIATION'), ('I', 'INTERVIEW')], default='M', max_length=1)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojss_app.Application')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojss_app.RecruiterProfile')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ojss_app.SeekerProfile')),
            ],
        ),
    ]
