# Generated by Django 2.0.4 on 2018-05-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0015_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='application_id',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recruiter_id',
            new_name='recruiter',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='seeker_id',
            new_name='seeker',
        ),
    ]
