# Generated by Django 2.0.4 on 2018-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0024_auto_20180509_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interview_description',
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('A', 'APPLICATION'), ('I', 'INTERVIEW')], default='M', max_length=1),
        ),
    ]
