# Generated by Django 2.0.4 on 2018-05-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0025_auto_20180509_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('A', 'APPLICATION'), ('I', 'INTERVIEW')], default='A', max_length=1),
        ),
    ]
