# Generated by Django 2.0.4 on 2018-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojss_app', '0028_auto_20180510_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerskillset',
            name='skill_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seekerskillset',
            name='skill_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seekerskillset',
            name='skill_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seekerskillset',
            name='skill_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
